//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace SnCore.Web.Soap.Tests.WebMarketingService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebMarketingServiceSoap", Namespace="http://www.vestris.com/sncore/ns/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitServiceOfCampaignAccountRecepient))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitServiceOfCampaign))]
    public partial class WebMarketingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCampaignsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampaignsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateCampaignOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCampaignOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampaignByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampaignAccountRecepientsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampaignAccountRecepientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateCampaignAccountRecepientOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCampaignAccountRecepientOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCampaignAccountRecepientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampaignAccountRecepientByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportCampaignAccountRecepientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportCampaignAccountEmailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportCampaignAccountLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportCampaignAccountPropertyValuesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebMarketingService() {
            this.Url = global::SnCore.Web.Soap.Tests.Properties.Settings.Default.SnCore_Web_Soap_Tests_WebMarketingService_WebMarketingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCampaignsCountCompletedEventHandler GetCampaignsCountCompleted;
        
        /// <remarks/>
        public event GetCampaignsCompletedEventHandler GetCampaignsCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateCampaignCompletedEventHandler CreateOrUpdateCampaignCompleted;
        
        /// <remarks/>
        public event DeleteCampaignCompletedEventHandler DeleteCampaignCompleted;
        
        /// <remarks/>
        public event GetCampaignByIdCompletedEventHandler GetCampaignByIdCompleted;
        
        /// <remarks/>
        public event GetCampaignAccountRecepientsCountCompletedEventHandler GetCampaignAccountRecepientsCountCompleted;
        
        /// <remarks/>
        public event GetCampaignAccountRecepientsCompletedEventHandler GetCampaignAccountRecepientsCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateCampaignAccountRecepientCompletedEventHandler CreateOrUpdateCampaignAccountRecepientCompleted;
        
        /// <remarks/>
        public event DeleteCampaignAccountRecepientCompletedEventHandler DeleteCampaignAccountRecepientCompleted;
        
        /// <remarks/>
        public event DeleteCampaignAccountRecepientsCompletedEventHandler DeleteCampaignAccountRecepientsCompleted;
        
        /// <remarks/>
        public event GetCampaignAccountRecepientByIdCompletedEventHandler GetCampaignAccountRecepientByIdCompleted;
        
        /// <remarks/>
        public event ImportCampaignAccountRecepientsCompletedEventHandler ImportCampaignAccountRecepientsCompleted;
        
        /// <remarks/>
        public event ImportCampaignAccountEmailsCompletedEventHandler ImportCampaignAccountEmailsCompleted;
        
        /// <remarks/>
        public event ImportCampaignAccountLocationCompletedEventHandler ImportCampaignAccountLocationCompleted;
        
        /// <remarks/>
        public event ImportCampaignAccountPropertyValuesCompletedEventHandler ImportCampaignAccountPropertyValuesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetCampaignsCount", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCampaignsCount(string ticket) {
            object[] results = this.Invoke("GetCampaignsCount", new object[] {
                        ticket});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCampaignsCountAsync(string ticket) {
            this.GetCampaignsCountAsync(ticket, null);
        }
        
        /// <remarks/>
        public void GetCampaignsCountAsync(string ticket, object userState) {
            if ((this.GetCampaignsCountOperationCompleted == null)) {
                this.GetCampaignsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampaignsCountOperationCompleted);
            }
            this.InvokeAsync("GetCampaignsCount", new object[] {
                        ticket}, this.GetCampaignsCountOperationCompleted, userState);
        }
        
        private void OnGetCampaignsCountOperationCompleted(object arg) {
            if ((this.GetCampaignsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampaignsCountCompleted(this, new GetCampaignsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetCampaigns", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitCampaign[] GetCampaigns(string ticket, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetCampaigns", new object[] {
                        ticket,
                        options});
            return ((TransitCampaign[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCampaignsAsync(string ticket, ServiceQueryOptions options) {
            this.GetCampaignsAsync(ticket, options, null);
        }
        
        /// <remarks/>
        public void GetCampaignsAsync(string ticket, ServiceQueryOptions options, object userState) {
            if ((this.GetCampaignsOperationCompleted == null)) {
                this.GetCampaignsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampaignsOperationCompleted);
            }
            this.InvokeAsync("GetCampaigns", new object[] {
                        ticket,
                        options}, this.GetCampaignsOperationCompleted, userState);
        }
        
        private void OnGetCampaignsOperationCompleted(object arg) {
            if ((this.GetCampaignsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampaignsCompleted(this, new GetCampaignsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/CreateOrUpdateCampaign", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateCampaign(string ticket, TransitCampaign campaign) {
            object[] results = this.Invoke("CreateOrUpdateCampaign", new object[] {
                        ticket,
                        campaign});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateCampaignAsync(string ticket, TransitCampaign campaign) {
            this.CreateOrUpdateCampaignAsync(ticket, campaign, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateCampaignAsync(string ticket, TransitCampaign campaign, object userState) {
            if ((this.CreateOrUpdateCampaignOperationCompleted == null)) {
                this.CreateOrUpdateCampaignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateCampaignOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateCampaign", new object[] {
                        ticket,
                        campaign}, this.CreateOrUpdateCampaignOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateCampaignOperationCompleted(object arg) {
            if ((this.CreateOrUpdateCampaignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateCampaignCompleted(this, new CreateOrUpdateCampaignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/DeleteCampaign", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCampaign(string ticket, int id) {
            this.Invoke("DeleteCampaign", new object[] {
                        ticket,
                        id});
        }
        
        /// <remarks/>
        public void DeleteCampaignAsync(string ticket, int id) {
            this.DeleteCampaignAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void DeleteCampaignAsync(string ticket, int id, object userState) {
            if ((this.DeleteCampaignOperationCompleted == null)) {
                this.DeleteCampaignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCampaignOperationCompleted);
            }
            this.InvokeAsync("DeleteCampaign", new object[] {
                        ticket,
                        id}, this.DeleteCampaignOperationCompleted, userState);
        }
        
        private void OnDeleteCampaignOperationCompleted(object arg) {
            if ((this.DeleteCampaignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCampaignCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetCampaignById", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitCampaign GetCampaignById(string ticket, int id) {
            object[] results = this.Invoke("GetCampaignById", new object[] {
                        ticket,
                        id});
            return ((TransitCampaign)(results[0]));
        }
        
        /// <remarks/>
        public void GetCampaignByIdAsync(string ticket, int id) {
            this.GetCampaignByIdAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetCampaignByIdAsync(string ticket, int id, object userState) {
            if ((this.GetCampaignByIdOperationCompleted == null)) {
                this.GetCampaignByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampaignByIdOperationCompleted);
            }
            this.InvokeAsync("GetCampaignById", new object[] {
                        ticket,
                        id}, this.GetCampaignByIdOperationCompleted, userState);
        }
        
        private void OnGetCampaignByIdOperationCompleted(object arg) {
            if ((this.GetCampaignByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampaignByIdCompleted(this, new GetCampaignByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetCampaignAccountRecepientsCount", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCampaignAccountRecepientsCount(string ticket, int id) {
            object[] results = this.Invoke("GetCampaignAccountRecepientsCount", new object[] {
                        ticket,
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCampaignAccountRecepientsCountAsync(string ticket, int id) {
            this.GetCampaignAccountRecepientsCountAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetCampaignAccountRecepientsCountAsync(string ticket, int id, object userState) {
            if ((this.GetCampaignAccountRecepientsCountOperationCompleted == null)) {
                this.GetCampaignAccountRecepientsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampaignAccountRecepientsCountOperationCompleted);
            }
            this.InvokeAsync("GetCampaignAccountRecepientsCount", new object[] {
                        ticket,
                        id}, this.GetCampaignAccountRecepientsCountOperationCompleted, userState);
        }
        
        private void OnGetCampaignAccountRecepientsCountOperationCompleted(object arg) {
            if ((this.GetCampaignAccountRecepientsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampaignAccountRecepientsCountCompleted(this, new GetCampaignAccountRecepientsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetCampaignAccountRecepients", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitCampaignAccountRecepient[] GetCampaignAccountRecepients(string ticket, int id, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetCampaignAccountRecepients", new object[] {
                        ticket,
                        id,
                        options});
            return ((TransitCampaignAccountRecepient[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCampaignAccountRecepientsAsync(string ticket, int id, ServiceQueryOptions options) {
            this.GetCampaignAccountRecepientsAsync(ticket, id, options, null);
        }
        
        /// <remarks/>
        public void GetCampaignAccountRecepientsAsync(string ticket, int id, ServiceQueryOptions options, object userState) {
            if ((this.GetCampaignAccountRecepientsOperationCompleted == null)) {
                this.GetCampaignAccountRecepientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampaignAccountRecepientsOperationCompleted);
            }
            this.InvokeAsync("GetCampaignAccountRecepients", new object[] {
                        ticket,
                        id,
                        options}, this.GetCampaignAccountRecepientsOperationCompleted, userState);
        }
        
        private void OnGetCampaignAccountRecepientsOperationCompleted(object arg) {
            if ((this.GetCampaignAccountRecepientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampaignAccountRecepientsCompleted(this, new GetCampaignAccountRecepientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/CreateOrUpdateCampaignAccountRecepient", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateCampaignAccountRecepient(string ticket, TransitCampaignAccountRecepient recepient) {
            object[] results = this.Invoke("CreateOrUpdateCampaignAccountRecepient", new object[] {
                        ticket,
                        recepient});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateCampaignAccountRecepientAsync(string ticket, TransitCampaignAccountRecepient recepient) {
            this.CreateOrUpdateCampaignAccountRecepientAsync(ticket, recepient, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateCampaignAccountRecepientAsync(string ticket, TransitCampaignAccountRecepient recepient, object userState) {
            if ((this.CreateOrUpdateCampaignAccountRecepientOperationCompleted == null)) {
                this.CreateOrUpdateCampaignAccountRecepientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateCampaignAccountRecepientOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateCampaignAccountRecepient", new object[] {
                        ticket,
                        recepient}, this.CreateOrUpdateCampaignAccountRecepientOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateCampaignAccountRecepientOperationCompleted(object arg) {
            if ((this.CreateOrUpdateCampaignAccountRecepientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateCampaignAccountRecepientCompleted(this, new CreateOrUpdateCampaignAccountRecepientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/DeleteCampaignAccountRecepient", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCampaignAccountRecepient(string ticket, int id) {
            this.Invoke("DeleteCampaignAccountRecepient", new object[] {
                        ticket,
                        id});
        }
        
        /// <remarks/>
        public void DeleteCampaignAccountRecepientAsync(string ticket, int id) {
            this.DeleteCampaignAccountRecepientAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void DeleteCampaignAccountRecepientAsync(string ticket, int id, object userState) {
            if ((this.DeleteCampaignAccountRecepientOperationCompleted == null)) {
                this.DeleteCampaignAccountRecepientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCampaignAccountRecepientOperationCompleted);
            }
            this.InvokeAsync("DeleteCampaignAccountRecepient", new object[] {
                        ticket,
                        id}, this.DeleteCampaignAccountRecepientOperationCompleted, userState);
        }
        
        private void OnDeleteCampaignAccountRecepientOperationCompleted(object arg) {
            if ((this.DeleteCampaignAccountRecepientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCampaignAccountRecepientCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/DeleteCampaignAccountRecepients", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCampaignAccountRecepients(string ticket, int id) {
            this.Invoke("DeleteCampaignAccountRecepients", new object[] {
                        ticket,
                        id});
        }
        
        /// <remarks/>
        public void DeleteCampaignAccountRecepientsAsync(string ticket, int id) {
            this.DeleteCampaignAccountRecepientsAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void DeleteCampaignAccountRecepientsAsync(string ticket, int id, object userState) {
            if ((this.DeleteCampaignAccountRecepientsOperationCompleted == null)) {
                this.DeleteCampaignAccountRecepientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCampaignAccountRecepientsOperationCompleted);
            }
            this.InvokeAsync("DeleteCampaignAccountRecepients", new object[] {
                        ticket,
                        id}, this.DeleteCampaignAccountRecepientsOperationCompleted, userState);
        }
        
        private void OnDeleteCampaignAccountRecepientsOperationCompleted(object arg) {
            if ((this.DeleteCampaignAccountRecepientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCampaignAccountRecepientsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetCampaignAccountRecepientById", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitCampaignAccountRecepient GetCampaignAccountRecepientById(string ticket, int id) {
            object[] results = this.Invoke("GetCampaignAccountRecepientById", new object[] {
                        ticket,
                        id});
            return ((TransitCampaignAccountRecepient)(results[0]));
        }
        
        /// <remarks/>
        public void GetCampaignAccountRecepientByIdAsync(string ticket, int id) {
            this.GetCampaignAccountRecepientByIdAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetCampaignAccountRecepientByIdAsync(string ticket, int id, object userState) {
            if ((this.GetCampaignAccountRecepientByIdOperationCompleted == null)) {
                this.GetCampaignAccountRecepientByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampaignAccountRecepientByIdOperationCompleted);
            }
            this.InvokeAsync("GetCampaignAccountRecepientById", new object[] {
                        ticket,
                        id}, this.GetCampaignAccountRecepientByIdOperationCompleted, userState);
        }
        
        private void OnGetCampaignAccountRecepientByIdOperationCompleted(object arg) {
            if ((this.GetCampaignAccountRecepientByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampaignAccountRecepientByIdCompleted(this, new GetCampaignAccountRecepientByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/ImportCampaignAccountRecepients", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ImportCampaignAccountRecepients(string ticket, TransitCampaignAccountRecepient[] recepients) {
            object[] results = this.Invoke("ImportCampaignAccountRecepients", new object[] {
                        ticket,
                        recepients});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ImportCampaignAccountRecepientsAsync(string ticket, TransitCampaignAccountRecepient[] recepients) {
            this.ImportCampaignAccountRecepientsAsync(ticket, recepients, null);
        }
        
        /// <remarks/>
        public void ImportCampaignAccountRecepientsAsync(string ticket, TransitCampaignAccountRecepient[] recepients, object userState) {
            if ((this.ImportCampaignAccountRecepientsOperationCompleted == null)) {
                this.ImportCampaignAccountRecepientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportCampaignAccountRecepientsOperationCompleted);
            }
            this.InvokeAsync("ImportCampaignAccountRecepients", new object[] {
                        ticket,
                        recepients}, this.ImportCampaignAccountRecepientsOperationCompleted, userState);
        }
        
        private void OnImportCampaignAccountRecepientsOperationCompleted(object arg) {
            if ((this.ImportCampaignAccountRecepientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportCampaignAccountRecepientsCompleted(this, new ImportCampaignAccountRecepientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/ImportCampaignAccountEmails", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ImportCampaignAccountEmails(string ticket, int campaign_id, bool verified_emails, bool unverified_emails) {
            object[] results = this.Invoke("ImportCampaignAccountEmails", new object[] {
                        ticket,
                        campaign_id,
                        verified_emails,
                        unverified_emails});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ImportCampaignAccountEmailsAsync(string ticket, int campaign_id, bool verified_emails, bool unverified_emails) {
            this.ImportCampaignAccountEmailsAsync(ticket, campaign_id, verified_emails, unverified_emails, null);
        }
        
        /// <remarks/>
        public void ImportCampaignAccountEmailsAsync(string ticket, int campaign_id, bool verified_emails, bool unverified_emails, object userState) {
            if ((this.ImportCampaignAccountEmailsOperationCompleted == null)) {
                this.ImportCampaignAccountEmailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportCampaignAccountEmailsOperationCompleted);
            }
            this.InvokeAsync("ImportCampaignAccountEmails", new object[] {
                        ticket,
                        campaign_id,
                        verified_emails,
                        unverified_emails}, this.ImportCampaignAccountEmailsOperationCompleted, userState);
        }
        
        private void OnImportCampaignAccountEmailsOperationCompleted(object arg) {
            if ((this.ImportCampaignAccountEmailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportCampaignAccountEmailsCompleted(this, new ImportCampaignAccountEmailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/ImportCampaignAccountLocation", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ImportCampaignAccountLocation(string ticket, int campaign_id, string country, string state, string city) {
            object[] results = this.Invoke("ImportCampaignAccountLocation", new object[] {
                        ticket,
                        campaign_id,
                        country,
                        state,
                        city});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ImportCampaignAccountLocationAsync(string ticket, int campaign_id, string country, string state, string city) {
            this.ImportCampaignAccountLocationAsync(ticket, campaign_id, country, state, city, null);
        }
        
        /// <remarks/>
        public void ImportCampaignAccountLocationAsync(string ticket, int campaign_id, string country, string state, string city, object userState) {
            if ((this.ImportCampaignAccountLocationOperationCompleted == null)) {
                this.ImportCampaignAccountLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportCampaignAccountLocationOperationCompleted);
            }
            this.InvokeAsync("ImportCampaignAccountLocation", new object[] {
                        ticket,
                        campaign_id,
                        country,
                        state,
                        city}, this.ImportCampaignAccountLocationOperationCompleted, userState);
        }
        
        private void OnImportCampaignAccountLocationOperationCompleted(object arg) {
            if ((this.ImportCampaignAccountLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportCampaignAccountLocationCompleted(this, new ImportCampaignAccountLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/ImportCampaignAccountPropertyValues", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ImportCampaignAccountPropertyValues(string ticket, int campaign_id, int pid, string value, bool unset) {
            object[] results = this.Invoke("ImportCampaignAccountPropertyValues", new object[] {
                        ticket,
                        campaign_id,
                        pid,
                        value,
                        unset});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ImportCampaignAccountPropertyValuesAsync(string ticket, int campaign_id, int pid, string value, bool unset) {
            this.ImportCampaignAccountPropertyValuesAsync(ticket, campaign_id, pid, value, unset, null);
        }
        
        /// <remarks/>
        public void ImportCampaignAccountPropertyValuesAsync(string ticket, int campaign_id, int pid, string value, bool unset, object userState) {
            if ((this.ImportCampaignAccountPropertyValuesOperationCompleted == null)) {
                this.ImportCampaignAccountPropertyValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportCampaignAccountPropertyValuesOperationCompleted);
            }
            this.InvokeAsync("ImportCampaignAccountPropertyValues", new object[] {
                        ticket,
                        campaign_id,
                        pid,
                        value,
                        unset}, this.ImportCampaignAccountPropertyValuesOperationCompleted, userState);
        }
        
        private void OnImportCampaignAccountPropertyValuesOperationCompleted(object arg) {
            if ((this.ImportCampaignAccountPropertyValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportCampaignAccountPropertyValuesCompleted(this, new ImportCampaignAccountPropertyValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class ServiceQueryOptions {
        
        private int pageSizeField;
        
        private int pageNumberField;
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitCampaignAccountRecepient))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public abstract partial class TransitServiceOfCampaignAccountRecepient {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class TransitCampaignAccountRecepient : TransitServiceOfCampaignAccountRecepient {
        
        private int campaignIdField;
        
        private int accountIdField;
        
        private bool sentField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        private string lastErrorField;
        
        /// <remarks/>
        public int CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
            }
        }
        
        /// <remarks/>
        public int AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        public string LastError {
            get {
                return this.lastErrorField;
            }
            set {
                this.lastErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitCampaign))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public abstract partial class TransitServiceOfCampaign {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class TransitCampaign : TransitServiceOfCampaign {
        
        private string nameField;
        
        private string descriptionField;
        
        private string senderNameField;
        
        private string senderEmailAddressField;
        
        private string urlField;
        
        private bool activeField;
        
        private System.DateTime processedField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string SenderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderEmailAddress {
            get {
                return this.senderEmailAddressField;
            }
            set {
                this.senderEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetCampaignsCountCompletedEventHandler(object sender, GetCampaignsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampaignsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampaignsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetCampaignsCompletedEventHandler(object sender, GetCampaignsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampaignsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampaignsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitCampaign[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitCampaign[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateOrUpdateCampaignCompletedEventHandler(object sender, CreateOrUpdateCampaignCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateCampaignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateCampaignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DeleteCampaignCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetCampaignByIdCompletedEventHandler(object sender, GetCampaignByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampaignByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampaignByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitCampaign Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitCampaign)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetCampaignAccountRecepientsCountCompletedEventHandler(object sender, GetCampaignAccountRecepientsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampaignAccountRecepientsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampaignAccountRecepientsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetCampaignAccountRecepientsCompletedEventHandler(object sender, GetCampaignAccountRecepientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampaignAccountRecepientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampaignAccountRecepientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitCampaignAccountRecepient[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitCampaignAccountRecepient[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateOrUpdateCampaignAccountRecepientCompletedEventHandler(object sender, CreateOrUpdateCampaignAccountRecepientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateCampaignAccountRecepientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateCampaignAccountRecepientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DeleteCampaignAccountRecepientCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DeleteCampaignAccountRecepientsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetCampaignAccountRecepientByIdCompletedEventHandler(object sender, GetCampaignAccountRecepientByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampaignAccountRecepientByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampaignAccountRecepientByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitCampaignAccountRecepient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitCampaignAccountRecepient)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ImportCampaignAccountRecepientsCompletedEventHandler(object sender, ImportCampaignAccountRecepientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportCampaignAccountRecepientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportCampaignAccountRecepientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ImportCampaignAccountEmailsCompletedEventHandler(object sender, ImportCampaignAccountEmailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportCampaignAccountEmailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportCampaignAccountEmailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ImportCampaignAccountLocationCompletedEventHandler(object sender, ImportCampaignAccountLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportCampaignAccountLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportCampaignAccountLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ImportCampaignAccountPropertyValuesCompletedEventHandler(object sender, ImportCampaignAccountPropertyValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportCampaignAccountPropertyValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportCampaignAccountPropertyValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591