//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIME.NET.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MimeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MimeMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MIME.NET.Tests.MimeMessages", typeof(MimeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: postmaster@vestris.com
        ///To: admin@foodcandy.com
        ///Date: Sat, 17 May 2008 11:51:46 -0400
        ///MIME-Version: 1.0
        ///Content-Type: multipart/report; report-type=delivery-status;
        ///	boundary=&quot;9B095B5ADSN=_01C8B829A12D30BE000000DDIPDMBZ0465MIA.ci&quot;
        ///X-DSNContext: 7ce717b1 - 1194 - 00000002 - 00000000
        ///Message-ID: &lt;GCIFoPkG000000097@IPDMBZ0465MIA.citrus.com&gt;
        ///Subject: Delivery Status Notification (Failure)
        ///
        ///This is a MIME-formatted message.  
        ///Portions of this message may be unreadable without a MIME-capable mail  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BinaryNDR {
            get {
                return ResourceManager.GetString("BinaryNDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: postmaster@vestris.com
        ///To: fleming@dimaks.com
        ///Date: Fri, 23 Nov 2007 11:39:55 -0500
        ///MIME-Version: 1.0
        ///Content-Type: multipart/report; report-type=delivery-status;
        ///	boundary=&quot;9B095B5ADSN=_01C82DEF2F8529240000053AIPDMBZ0465MIA.ci&quot;
        ///X-DSNContext: 335a7efd - 4523 - 00000001 - 80040546
        ///Message-ID: &lt;S2TRqf69a00000017@IPDMBZ0465MIA.citrus.com&gt;
        ///Subject: Delivery Status Notification (Failure)
        ///
        ///This is a MIME-formatted message.  
        ///Portions of this message may be unreadable without a MIME-capable mail p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleNDR {
            get {
                return ResourceManager.GetString("SimpleNDR", resourceCulture);
            }
        }
    }
}
