BULK INSERT Configuration FROM 'Configuration.txt' WITH ( KEEPIDENTITY )
BULK INSERT Country FROM 'Country.txt' WITH ( KEEPIDENTITY )
BULK INSERT State FROM 'State.txt' WITH ( KEEPIDENTITY )
BULK INSERT City FROM 'City.txt' WITH ( KEEPIDENTITY )
BULK INSERT BugSeverity FROM 'BugSeverity.txt' WITH ( KEEPIDENTITY )
BULK INSERT BugStatus FROM 'BugStatus.txt' WITH ( KEEPIDENTITY )
BULK INSERT BugType FROM 'BugType.txt' WITH ( KEEPIDENTITY )
BULK INSERT BugPriority FROM 'BugPriority.txt' WITH ( KEEPIDENTITY )
BULK INSERT BugResolution FROM 'BugResolution.txt' WITH ( KEEPIDENTITY )
BULK INSERT PictureType FROM 'PictureType.txt' WITH ( KEEPIDENTITY )
BULK INSERT AccountFlagType FROM 'AccountFlagType.txt' WITH ( KEEPIDENTITY )
BULK INSERT AccountFlagType FROM 'AccountEventType.txt' WITH ( KEEPIDENTITY )
BULK INSERT AccountFlagType FROM 'AccountPlaceType.txt' WITH ( KEEPIDENTITY )
BULK INSERT FeedType FROM 'FeedType.txt' WITH ( KEEPIDENTITY )

