using System;
using System.Collections.Generic;
using System.Text;
using System.Net.Mail;

namespace MIME
{
    /// <summary>
    /// A DSN contains information about attempts to deliver a message to one
    /// or more recipients.  The delivery information for any particular
    /// recipient is contained in a group of contiguous per-recipient fields.
    /// Each group of per-recipient fields is preceded by a blank line.
    /// </summary>
    public class MimeDSNRecipient : MimeHeader
    {
        public MimeDSNRecipient()
        {

        }

        /// <summary>
        /// The Original-Recipient field indicates the original recipient address
        /// as specified by the sender of the message for which the DSN is being
        /// issued.
        /// </summary>
        public string OriginalRecipient
        {
            get
            {
                return GetFieldValue("Original-Recipient");
            }
            set
            {
                SetFieldValue("Original-Recipient", value);
            }
        }

        /// <summary>
        /// The Final-Recipient field indicates the recipient for which this set
        /// of per-recipient fields applies.  This field MUST be present in each
        /// set of per-recipient data.
        /// </summary>
        public string FinalRecipient
        {
            get
            {
                return GetFieldValue("Final-Recipient");
            }
            set
            {
                SetFieldValue("Final-Recipient", value);
            }
        }

        public string FinalRecipientEmailAddress
        {
            get
            {
                string recip = FinalRecipient;
                int sc = recip.IndexOf(";");
                if (sc >= 0) recip = recip.Substring(sc + 1, recip.Length - sc - 1);
                MailAddress address = new MailAddress(recip);
                return address.Address;
            }
        }

        /// <summary>
        /// The Action field indicates the action performed by the Reporting-MTA
        /// as a result of its attempt to deliver the message to this recipient
        /// address.  This field MUST be present for each recipient named in the
        /// DSN.
        /// </summary>
        public string Action
        {
            get
            {
                return GetFieldValue("Action");
            }
            set
            {
                SetFieldValue("Action", value);
            }
        }

        /// <summary>
        /// The per-recipient Status field contains a transport-independent
        /// status code which indicates the delivery status of the message to
        /// that recipient.  This field MUST be present for each delivery attempt
        /// which is described by a DSN.
        /// </summary>
        public string Status
        {
            get
            {
                return GetFieldValue("Status");
            }
            set
            {
                SetFieldValue("Status", value);
            }
        }

        /// <summary>
        /// The value associated with the Remote-MTA DSN field is a printable
        /// ASCII representation of the name of the "remote" MTA that reported
        /// delivery status to the "reporting" MTA.
        /// </summary>
        public string RemoteMTA
        {
            get
            {
                return GetFieldValue("Remote-MTA");
            }
            set
            {
                SetFieldValue("Remote-MTA", value);
            }
        }

        /// <summary>
        /// For a "failed" or "delayed" recipient, the Diagnostic-Code DSN field
        /// contains the actual diagnostic code issued by the mail transport.
        /// Since such codes vary from one mail transport to another, the
        /// diagnostic-type subfield is needed to specify which type of
        /// diagnostic code is represented.
        /// </summary>
        public string DiagnosticCode
        {
            get
            {
                return GetFieldValue("Diagnostic-Code");
            }
            set
            {
                SetFieldValue("Diagnostic-Code", value);
            }
        }

        /// <summary>
        /// The Last-Attempt-Date field gives the date and time of the last
        /// attempt to relay, gateway, or deliver the message (whether successful
        /// or unsuccessful) by the Reporting MTA.  This is not necessarily the
        /// same as the value of the Date field from the header of the message
        /// used to transmit this delivery status notification: In cases where
        /// the DSN was generated by a gateway, the Date field in the message
        /// header contains the time the DSN was sent by the gateway and the DSN
        /// Last-Attempt-Date field contains the time the last delivery attempt
        /// occurred.
        /// </summary>
        public string LastAttemptDate
        {
            get
            {
                return GetFieldValue("Last-Attempt-Date");
            }
            set
            {
                SetFieldValue("Last-Attempt-Date", value);
            }
        }

        /// todo: final-log-id , Will-Retry-Until
    }
}
