//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnCore.Web.Soap.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebAccountService.asmx")]
        public string SnCore_Web_Soap_Tests_WebAccountService_WebAccountService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebAccountService_WebAccountService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dblock-black.orangebitch.com/SnCoreWeb/WebAccountService.asmx")]
        public string SnCore_Web_Soap_Tests_WebAccountService_WebAccountService1 {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebAccountService_WebAccountService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dblock-black.orangebitch.com/SnCoreWeb/WebAccountService.asmx")]
        public string SnCore_Web_Soap_Tests_WebAccountService_WebAccountService11 {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebAccountService_WebAccountService11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebSystemService.asmx")]
        public string SnCore_Web_Soap_Tests_WebSystemService_WebSystemService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebSystemService_WebSystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebStatsService.asmx")]
        public string SnCore_Web_Soap_Tests_WebStatsService_WebStatsService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebStatsService_WebStatsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebBugService.asmx")]
        public string SnCore_Web_Soap_Tests_WebBugService_WebBugService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebBugService_WebBugService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebLicenseService.asmx")]
        public string SnCore_Web_Soap_Tests_WebLicenseService_WebLicenseService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebLicenseService_WebLicenseService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebContentService.asmx")]
        public string SnCore_Web_Soap_Tests_WebContentService_WebContentService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebContentService_WebContentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebLocationService.asmx")]
        public string SnCore_Web_Soap_Tests_WebLocationService_WebLocationService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebLocationService_WebLocationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebMadLibService.asmx")]
        public string SnCore_Web_Soap_Tests_WebMadLibService_WebMadLibService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebMadLibService_WebMadLibService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebStoryService.asmx")]
        public string SnCore_Web_Soap_Tests_WebStoryService_WebStoryService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebStoryService_WebStoryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebTagWordService.asmx")]
        public string SnCore_Web_Soap_Tests_WebTagWordService_WebTagWordService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebTagWordService_WebTagWordService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebSyndicationService.asmx")]
        public string SnCore_Web_Soap_Tests_WebSyndicationService_WebSyndicationService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebSyndicationService_WebSyndicationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebSocialService.asmx")]
        public string SnCore_Web_Soap_Tests_WebSocialService_WebSocialService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebSocialService_WebSocialService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebMarketingService.asmx")]
        public string SnCore_Web_Soap_Tests_WebMarketingService_WebMarketingService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebMarketingService_WebMarketingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebBlogService.asmx")]
        public string SnCore_Web_Soap_Tests_WebBlogService_WebBlogService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebBlogService_WebBlogService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebEventService.asmx")]
        public string SnCore_Web_Soap_Tests_WebEventService_WebEventService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebEventService_WebEventService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebPlaceService.asmx")]
        public string SnCore_Web_Soap_Tests_WebPlaceService_WebPlaceService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebPlaceService_WebPlaceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebDiscussionService.asmx")]
        public string SnCore_Web_Soap_Tests_WebDiscussionService_WebDiscussionService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebDiscussionService_WebDiscussionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebObjectService.asmx")]
        public string SnCore_Web_Soap_Tests_WebObjectService_WebObjectService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebObjectService_WebObjectService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SnCoreWeb/WebGroupService.asmx")]
        public string SnCore_Web_Soap_Tests_WebGroupService_WebGroupService {
            get {
                return ((string)(this["SnCore_Web_Soap_Tests_WebGroupService_WebGroupService"]));
            }
        }
    }
}
