//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace SnCore.Web.Soap.Tests.WebSocialService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebSocialServiceSoap", Namespace="http://www.vestris.com/sncore/ns/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitServiceOfAccountFriend))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitServiceOfAccountFriendRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitServiceOfAccount))]
    public partial class WebSocialService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNewAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountActivityCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNDegreeCountByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFirstDegreeCountByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendsAccountActivityCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendsAccountActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateAccountFriendRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcceptAccountFriendRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectAccountFriendRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSentAccountFriendRequestsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountFriendRequestsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSentAccountFriendRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountFriendRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAccountFriendRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountFriendRequestByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAccountFriendOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountFriendsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountFriendsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebSocialService() {
            this.Url = global::SnCore.Web.Soap.Tests.Properties.Settings.Default.SnCore_Web_Soap_Tests_WebSocialService_WebSocialService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNewAccountsCompletedEventHandler GetNewAccountsCompleted;
        
        /// <remarks/>
        public event GetActiveAccountsCompletedEventHandler GetActiveAccountsCompleted;
        
        /// <remarks/>
        public event GetAccountActivityCountCompletedEventHandler GetAccountActivityCountCompleted;
        
        /// <remarks/>
        public event GetAccountActivityCompletedEventHandler GetAccountActivityCompleted;
        
        /// <remarks/>
        public event GetNDegreeCountByIdCompletedEventHandler GetNDegreeCountByIdCompleted;
        
        /// <remarks/>
        public event GetFirstDegreeCountByIdCompletedEventHandler GetFirstDegreeCountByIdCompleted;
        
        /// <remarks/>
        public event GetFriendsAccountActivityCountCompletedEventHandler GetFriendsAccountActivityCountCompleted;
        
        /// <remarks/>
        public event GetFriendsAccountActivityCompletedEventHandler GetFriendsAccountActivityCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateAccountFriendRequestCompletedEventHandler CreateOrUpdateAccountFriendRequestCompleted;
        
        /// <remarks/>
        public event AcceptAccountFriendRequestCompletedEventHandler AcceptAccountFriendRequestCompleted;
        
        /// <remarks/>
        public event RejectAccountFriendRequestCompletedEventHandler RejectAccountFriendRequestCompleted;
        
        /// <remarks/>
        public event GetSentAccountFriendRequestsCountCompletedEventHandler GetSentAccountFriendRequestsCountCompleted;
        
        /// <remarks/>
        public event GetAccountFriendRequestsCountCompletedEventHandler GetAccountFriendRequestsCountCompleted;
        
        /// <remarks/>
        public event GetSentAccountFriendRequestsCompletedEventHandler GetSentAccountFriendRequestsCompleted;
        
        /// <remarks/>
        public event GetAccountFriendRequestsCompletedEventHandler GetAccountFriendRequestsCompleted;
        
        /// <remarks/>
        public event DeleteAccountFriendRequestCompletedEventHandler DeleteAccountFriendRequestCompleted;
        
        /// <remarks/>
        public event GetAccountFriendRequestByIdCompletedEventHandler GetAccountFriendRequestByIdCompleted;
        
        /// <remarks/>
        public event DeleteAccountFriendCompletedEventHandler DeleteAccountFriendCompleted;
        
        /// <remarks/>
        public event GetAccountFriendsCountCompletedEventHandler GetAccountFriendsCountCompleted;
        
        /// <remarks/>
        public event GetAccountFriendsCompletedEventHandler GetAccountFriendsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetNewAccounts", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccount[] GetNewAccounts(string ticket, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetNewAccounts", new object[] {
                        ticket,
                        options});
            return ((TransitAccount[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNewAccountsAsync(string ticket, ServiceQueryOptions options) {
            this.GetNewAccountsAsync(ticket, options, null);
        }
        
        /// <remarks/>
        public void GetNewAccountsAsync(string ticket, ServiceQueryOptions options, object userState) {
            if ((this.GetNewAccountsOperationCompleted == null)) {
                this.GetNewAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewAccountsOperationCompleted);
            }
            this.InvokeAsync("GetNewAccounts", new object[] {
                        ticket,
                        options}, this.GetNewAccountsOperationCompleted, userState);
        }
        
        private void OnGetNewAccountsOperationCompleted(object arg) {
            if ((this.GetNewAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewAccountsCompleted(this, new GetNewAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetActiveAccounts", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccount[] GetActiveAccounts(string ticket, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetActiveAccounts", new object[] {
                        ticket,
                        options});
            return ((TransitAccount[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveAccountsAsync(string ticket, ServiceQueryOptions options) {
            this.GetActiveAccountsAsync(ticket, options, null);
        }
        
        /// <remarks/>
        public void GetActiveAccountsAsync(string ticket, ServiceQueryOptions options, object userState) {
            if ((this.GetActiveAccountsOperationCompleted == null)) {
                this.GetActiveAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveAccountsOperationCompleted);
            }
            this.InvokeAsync("GetActiveAccounts", new object[] {
                        ticket,
                        options}, this.GetActiveAccountsOperationCompleted, userState);
        }
        
        private void OnGetActiveAccountsOperationCompleted(object arg) {
            if ((this.GetActiveAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveAccountsCompleted(this, new GetActiveAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetAccountActivityCount", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetAccountActivityCount(string ticket, AccountActivityQueryOptions queryoptions) {
            object[] results = this.Invoke("GetAccountActivityCount", new object[] {
                        ticket,
                        queryoptions});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountActivityCountAsync(string ticket, AccountActivityQueryOptions queryoptions) {
            this.GetAccountActivityCountAsync(ticket, queryoptions, null);
        }
        
        /// <remarks/>
        public void GetAccountActivityCountAsync(string ticket, AccountActivityQueryOptions queryoptions, object userState) {
            if ((this.GetAccountActivityCountOperationCompleted == null)) {
                this.GetAccountActivityCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountActivityCountOperationCompleted);
            }
            this.InvokeAsync("GetAccountActivityCount", new object[] {
                        ticket,
                        queryoptions}, this.GetAccountActivityCountOperationCompleted, userState);
        }
        
        private void OnGetAccountActivityCountOperationCompleted(object arg) {
            if ((this.GetAccountActivityCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountActivityCountCompleted(this, new GetAccountActivityCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetAccountActivity", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccountActivity[] GetAccountActivity(string ticket, AccountActivityQueryOptions queryoptions, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetAccountActivity", new object[] {
                        ticket,
                        queryoptions,
                        options});
            return ((TransitAccountActivity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountActivityAsync(string ticket, AccountActivityQueryOptions queryoptions, ServiceQueryOptions options) {
            this.GetAccountActivityAsync(ticket, queryoptions, options, null);
        }
        
        /// <remarks/>
        public void GetAccountActivityAsync(string ticket, AccountActivityQueryOptions queryoptions, ServiceQueryOptions options, object userState) {
            if ((this.GetAccountActivityOperationCompleted == null)) {
                this.GetAccountActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountActivityOperationCompleted);
            }
            this.InvokeAsync("GetAccountActivity", new object[] {
                        ticket,
                        queryoptions,
                        options}, this.GetAccountActivityOperationCompleted, userState);
        }
        
        private void OnGetAccountActivityOperationCompleted(object arg) {
            if ((this.GetAccountActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountActivityCompleted(this, new GetAccountActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetNDegreeCountById", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNDegreeCountById(string ticket, int id, int deg) {
            object[] results = this.Invoke("GetNDegreeCountById", new object[] {
                        ticket,
                        id,
                        deg});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNDegreeCountByIdAsync(string ticket, int id, int deg) {
            this.GetNDegreeCountByIdAsync(ticket, id, deg, null);
        }
        
        /// <remarks/>
        public void GetNDegreeCountByIdAsync(string ticket, int id, int deg, object userState) {
            if ((this.GetNDegreeCountByIdOperationCompleted == null)) {
                this.GetNDegreeCountByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNDegreeCountByIdOperationCompleted);
            }
            this.InvokeAsync("GetNDegreeCountById", new object[] {
                        ticket,
                        id,
                        deg}, this.GetNDegreeCountByIdOperationCompleted, userState);
        }
        
        private void OnGetNDegreeCountByIdOperationCompleted(object arg) {
            if ((this.GetNDegreeCountByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNDegreeCountByIdCompleted(this, new GetNDegreeCountByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetFirstDegreeCountById", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetFirstDegreeCountById(string ticket, int id) {
            object[] results = this.Invoke("GetFirstDegreeCountById", new object[] {
                        ticket,
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetFirstDegreeCountByIdAsync(string ticket, int id) {
            this.GetFirstDegreeCountByIdAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetFirstDegreeCountByIdAsync(string ticket, int id, object userState) {
            if ((this.GetFirstDegreeCountByIdOperationCompleted == null)) {
                this.GetFirstDegreeCountByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFirstDegreeCountByIdOperationCompleted);
            }
            this.InvokeAsync("GetFirstDegreeCountById", new object[] {
                        ticket,
                        id}, this.GetFirstDegreeCountByIdOperationCompleted, userState);
        }
        
        private void OnGetFirstDegreeCountByIdOperationCompleted(object arg) {
            if ((this.GetFirstDegreeCountByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFirstDegreeCountByIdCompleted(this, new GetFirstDegreeCountByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetFriendsAccountActivityCount", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetFriendsAccountActivityCount(string ticket, int id) {
            object[] results = this.Invoke("GetFriendsAccountActivityCount", new object[] {
                        ticket,
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendsAccountActivityCountAsync(string ticket, int id) {
            this.GetFriendsAccountActivityCountAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetFriendsAccountActivityCountAsync(string ticket, int id, object userState) {
            if ((this.GetFriendsAccountActivityCountOperationCompleted == null)) {
                this.GetFriendsAccountActivityCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendsAccountActivityCountOperationCompleted);
            }
            this.InvokeAsync("GetFriendsAccountActivityCount", new object[] {
                        ticket,
                        id}, this.GetFriendsAccountActivityCountOperationCompleted, userState);
        }
        
        private void OnGetFriendsAccountActivityCountOperationCompleted(object arg) {
            if ((this.GetFriendsAccountActivityCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendsAccountActivityCountCompleted(this, new GetFriendsAccountActivityCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetFriendsAccountActivity", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccountActivity[] GetFriendsAccountActivity(string ticket, int id, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetFriendsAccountActivity", new object[] {
                        ticket,
                        id,
                        options});
            return ((TransitAccountActivity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendsAccountActivityAsync(string ticket, int id, ServiceQueryOptions options) {
            this.GetFriendsAccountActivityAsync(ticket, id, options, null);
        }
        
        /// <remarks/>
        public void GetFriendsAccountActivityAsync(string ticket, int id, ServiceQueryOptions options, object userState) {
            if ((this.GetFriendsAccountActivityOperationCompleted == null)) {
                this.GetFriendsAccountActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendsAccountActivityOperationCompleted);
            }
            this.InvokeAsync("GetFriendsAccountActivity", new object[] {
                        ticket,
                        id,
                        options}, this.GetFriendsAccountActivityOperationCompleted, userState);
        }
        
        private void OnGetFriendsAccountActivityOperationCompleted(object arg) {
            if ((this.GetFriendsAccountActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendsAccountActivityCompleted(this, new GetFriendsAccountActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/CreateOrUpdateAccountFriendRequest", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateAccountFriendRequest(string ticket, int friendid, string message) {
            object[] results = this.Invoke("CreateOrUpdateAccountFriendRequest", new object[] {
                        ticket,
                        friendid,
                        message});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateAccountFriendRequestAsync(string ticket, int friendid, string message) {
            this.CreateOrUpdateAccountFriendRequestAsync(ticket, friendid, message, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateAccountFriendRequestAsync(string ticket, int friendid, string message, object userState) {
            if ((this.CreateOrUpdateAccountFriendRequestOperationCompleted == null)) {
                this.CreateOrUpdateAccountFriendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateAccountFriendRequestOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateAccountFriendRequest", new object[] {
                        ticket,
                        friendid,
                        message}, this.CreateOrUpdateAccountFriendRequestOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateAccountFriendRequestOperationCompleted(object arg) {
            if ((this.CreateOrUpdateAccountFriendRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateAccountFriendRequestCompleted(this, new CreateOrUpdateAccountFriendRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/AcceptAccountFriendRequest", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AcceptAccountFriendRequest(string ticket, int id, string message) {
            this.Invoke("AcceptAccountFriendRequest", new object[] {
                        ticket,
                        id,
                        message});
        }
        
        /// <remarks/>
        public void AcceptAccountFriendRequestAsync(string ticket, int id, string message) {
            this.AcceptAccountFriendRequestAsync(ticket, id, message, null);
        }
        
        /// <remarks/>
        public void AcceptAccountFriendRequestAsync(string ticket, int id, string message, object userState) {
            if ((this.AcceptAccountFriendRequestOperationCompleted == null)) {
                this.AcceptAccountFriendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcceptAccountFriendRequestOperationCompleted);
            }
            this.InvokeAsync("AcceptAccountFriendRequest", new object[] {
                        ticket,
                        id,
                        message}, this.AcceptAccountFriendRequestOperationCompleted, userState);
        }
        
        private void OnAcceptAccountFriendRequestOperationCompleted(object arg) {
            if ((this.AcceptAccountFriendRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcceptAccountFriendRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/RejectAccountFriendRequest", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RejectAccountFriendRequest(string ticket, int id, string message) {
            this.Invoke("RejectAccountFriendRequest", new object[] {
                        ticket,
                        id,
                        message});
        }
        
        /// <remarks/>
        public void RejectAccountFriendRequestAsync(string ticket, int id, string message) {
            this.RejectAccountFriendRequestAsync(ticket, id, message, null);
        }
        
        /// <remarks/>
        public void RejectAccountFriendRequestAsync(string ticket, int id, string message, object userState) {
            if ((this.RejectAccountFriendRequestOperationCompleted == null)) {
                this.RejectAccountFriendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectAccountFriendRequestOperationCompleted);
            }
            this.InvokeAsync("RejectAccountFriendRequest", new object[] {
                        ticket,
                        id,
                        message}, this.RejectAccountFriendRequestOperationCompleted, userState);
        }
        
        private void OnRejectAccountFriendRequestOperationCompleted(object arg) {
            if ((this.RejectAccountFriendRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectAccountFriendRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetSentAccountFriendRequestsCount", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetSentAccountFriendRequestsCount(string ticket, int id) {
            object[] results = this.Invoke("GetSentAccountFriendRequestsCount", new object[] {
                        ticket,
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetSentAccountFriendRequestsCountAsync(string ticket, int id) {
            this.GetSentAccountFriendRequestsCountAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetSentAccountFriendRequestsCountAsync(string ticket, int id, object userState) {
            if ((this.GetSentAccountFriendRequestsCountOperationCompleted == null)) {
                this.GetSentAccountFriendRequestsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSentAccountFriendRequestsCountOperationCompleted);
            }
            this.InvokeAsync("GetSentAccountFriendRequestsCount", new object[] {
                        ticket,
                        id}, this.GetSentAccountFriendRequestsCountOperationCompleted, userState);
        }
        
        private void OnGetSentAccountFriendRequestsCountOperationCompleted(object arg) {
            if ((this.GetSentAccountFriendRequestsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSentAccountFriendRequestsCountCompleted(this, new GetSentAccountFriendRequestsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetAccountFriendRequestsCount", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetAccountFriendRequestsCount(string ticket, int id) {
            object[] results = this.Invoke("GetAccountFriendRequestsCount", new object[] {
                        ticket,
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountFriendRequestsCountAsync(string ticket, int id) {
            this.GetAccountFriendRequestsCountAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetAccountFriendRequestsCountAsync(string ticket, int id, object userState) {
            if ((this.GetAccountFriendRequestsCountOperationCompleted == null)) {
                this.GetAccountFriendRequestsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountFriendRequestsCountOperationCompleted);
            }
            this.InvokeAsync("GetAccountFriendRequestsCount", new object[] {
                        ticket,
                        id}, this.GetAccountFriendRequestsCountOperationCompleted, userState);
        }
        
        private void OnGetAccountFriendRequestsCountOperationCompleted(object arg) {
            if ((this.GetAccountFriendRequestsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountFriendRequestsCountCompleted(this, new GetAccountFriendRequestsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetSentAccountFriendRequests", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccountFriendRequest[] GetSentAccountFriendRequests(string ticket, int id, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetSentAccountFriendRequests", new object[] {
                        ticket,
                        id,
                        options});
            return ((TransitAccountFriendRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSentAccountFriendRequestsAsync(string ticket, int id, ServiceQueryOptions options) {
            this.GetSentAccountFriendRequestsAsync(ticket, id, options, null);
        }
        
        /// <remarks/>
        public void GetSentAccountFriendRequestsAsync(string ticket, int id, ServiceQueryOptions options, object userState) {
            if ((this.GetSentAccountFriendRequestsOperationCompleted == null)) {
                this.GetSentAccountFriendRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSentAccountFriendRequestsOperationCompleted);
            }
            this.InvokeAsync("GetSentAccountFriendRequests", new object[] {
                        ticket,
                        id,
                        options}, this.GetSentAccountFriendRequestsOperationCompleted, userState);
        }
        
        private void OnGetSentAccountFriendRequestsOperationCompleted(object arg) {
            if ((this.GetSentAccountFriendRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSentAccountFriendRequestsCompleted(this, new GetSentAccountFriendRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetAccountFriendRequests", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccountFriendRequest[] GetAccountFriendRequests(string ticket, int id, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetAccountFriendRequests", new object[] {
                        ticket,
                        id,
                        options});
            return ((TransitAccountFriendRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountFriendRequestsAsync(string ticket, int id, ServiceQueryOptions options) {
            this.GetAccountFriendRequestsAsync(ticket, id, options, null);
        }
        
        /// <remarks/>
        public void GetAccountFriendRequestsAsync(string ticket, int id, ServiceQueryOptions options, object userState) {
            if ((this.GetAccountFriendRequestsOperationCompleted == null)) {
                this.GetAccountFriendRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountFriendRequestsOperationCompleted);
            }
            this.InvokeAsync("GetAccountFriendRequests", new object[] {
                        ticket,
                        id,
                        options}, this.GetAccountFriendRequestsOperationCompleted, userState);
        }
        
        private void OnGetAccountFriendRequestsOperationCompleted(object arg) {
            if ((this.GetAccountFriendRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountFriendRequestsCompleted(this, new GetAccountFriendRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/DeleteAccountFriendRequest", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteAccountFriendRequest(string ticket, int id) {
            this.Invoke("DeleteAccountFriendRequest", new object[] {
                        ticket,
                        id});
        }
        
        /// <remarks/>
        public void DeleteAccountFriendRequestAsync(string ticket, int id) {
            this.DeleteAccountFriendRequestAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void DeleteAccountFriendRequestAsync(string ticket, int id, object userState) {
            if ((this.DeleteAccountFriendRequestOperationCompleted == null)) {
                this.DeleteAccountFriendRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAccountFriendRequestOperationCompleted);
            }
            this.InvokeAsync("DeleteAccountFriendRequest", new object[] {
                        ticket,
                        id}, this.DeleteAccountFriendRequestOperationCompleted, userState);
        }
        
        private void OnDeleteAccountFriendRequestOperationCompleted(object arg) {
            if ((this.DeleteAccountFriendRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAccountFriendRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetAccountFriendRequestById", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccountFriendRequest GetAccountFriendRequestById(string ticket, int id) {
            object[] results = this.Invoke("GetAccountFriendRequestById", new object[] {
                        ticket,
                        id});
            return ((TransitAccountFriendRequest)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountFriendRequestByIdAsync(string ticket, int id) {
            this.GetAccountFriendRequestByIdAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetAccountFriendRequestByIdAsync(string ticket, int id, object userState) {
            if ((this.GetAccountFriendRequestByIdOperationCompleted == null)) {
                this.GetAccountFriendRequestByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountFriendRequestByIdOperationCompleted);
            }
            this.InvokeAsync("GetAccountFriendRequestById", new object[] {
                        ticket,
                        id}, this.GetAccountFriendRequestByIdOperationCompleted, userState);
        }
        
        private void OnGetAccountFriendRequestByIdOperationCompleted(object arg) {
            if ((this.GetAccountFriendRequestByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountFriendRequestByIdCompleted(this, new GetAccountFriendRequestByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/DeleteAccountFriend", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteAccountFriend(string ticket, int id) {
            this.Invoke("DeleteAccountFriend", new object[] {
                        ticket,
                        id});
        }
        
        /// <remarks/>
        public void DeleteAccountFriendAsync(string ticket, int id) {
            this.DeleteAccountFriendAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void DeleteAccountFriendAsync(string ticket, int id, object userState) {
            if ((this.DeleteAccountFriendOperationCompleted == null)) {
                this.DeleteAccountFriendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAccountFriendOperationCompleted);
            }
            this.InvokeAsync("DeleteAccountFriend", new object[] {
                        ticket,
                        id}, this.DeleteAccountFriendOperationCompleted, userState);
        }
        
        private void OnDeleteAccountFriendOperationCompleted(object arg) {
            if ((this.DeleteAccountFriendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAccountFriendCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetAccountFriendsCount", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetAccountFriendsCount(string ticket, int id) {
            object[] results = this.Invoke("GetAccountFriendsCount", new object[] {
                        ticket,
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountFriendsCountAsync(string ticket, int id) {
            this.GetAccountFriendsCountAsync(ticket, id, null);
        }
        
        /// <remarks/>
        public void GetAccountFriendsCountAsync(string ticket, int id, object userState) {
            if ((this.GetAccountFriendsCountOperationCompleted == null)) {
                this.GetAccountFriendsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountFriendsCountOperationCompleted);
            }
            this.InvokeAsync("GetAccountFriendsCount", new object[] {
                        ticket,
                        id}, this.GetAccountFriendsCountOperationCompleted, userState);
        }
        
        private void OnGetAccountFriendsCountOperationCompleted(object arg) {
            if ((this.GetAccountFriendsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountFriendsCountCompleted(this, new GetAccountFriendsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.vestris.com/sncore/ns/GetAccountFriends", RequestNamespace="http://www.vestris.com/sncore/ns/", ResponseNamespace="http://www.vestris.com/sncore/ns/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitAccountFriend[] GetAccountFriends(string ticket, int id, ServiceQueryOptions options) {
            object[] results = this.Invoke("GetAccountFriends", new object[] {
                        ticket,
                        id,
                        options});
            return ((TransitAccountFriend[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountFriendsAsync(string ticket, int id, ServiceQueryOptions options) {
            this.GetAccountFriendsAsync(ticket, id, options, null);
        }
        
        /// <remarks/>
        public void GetAccountFriendsAsync(string ticket, int id, ServiceQueryOptions options, object userState) {
            if ((this.GetAccountFriendsOperationCompleted == null)) {
                this.GetAccountFriendsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountFriendsOperationCompleted);
            }
            this.InvokeAsync("GetAccountFriends", new object[] {
                        ticket,
                        id,
                        options}, this.GetAccountFriendsOperationCompleted, userState);
        }
        
        private void OnGetAccountFriendsOperationCompleted(object arg) {
            if ((this.GetAccountFriendsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountFriendsCompleted(this, new GetAccountFriendsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class ServiceQueryOptions {
        
        private int pageSizeField;
        
        private int pageNumberField;
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitAccountFriend))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public abstract partial class TransitServiceOfAccountFriend {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class TransitAccountFriend : TransitServiceOfAccountFriend {
        
        private int friendIdField;
        
        private int friendPictureIdField;
        
        private string friendNameField;
        
        private System.DateTime createdField;
        
        /// <remarks/>
        public int FriendId {
            get {
                return this.friendIdField;
            }
            set {
                this.friendIdField = value;
            }
        }
        
        /// <remarks/>
        public int FriendPictureId {
            get {
                return this.friendPictureIdField;
            }
            set {
                this.friendPictureIdField = value;
            }
        }
        
        /// <remarks/>
        public string FriendName {
            get {
                return this.friendNameField;
            }
            set {
                this.friendNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitAccountFriendRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public abstract partial class TransitServiceOfAccountFriendRequest {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class TransitAccountFriendRequest : TransitServiceOfAccountFriendRequest {
        
        private int accountIdField;
        
        private int accountPictureIdField;
        
        private string accountNameField;
        
        private int keenIdField;
        
        private int keenPictureIdField;
        
        private string keenNameField;
        
        private string messageField;
        
        private System.DateTime createdField;
        
        /// <remarks/>
        public int AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public int AccountPictureId {
            get {
                return this.accountPictureIdField;
            }
            set {
                this.accountPictureIdField = value;
            }
        }
        
        /// <remarks/>
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public int KeenId {
            get {
                return this.keenIdField;
            }
            set {
                this.keenIdField = value;
            }
        }
        
        /// <remarks/>
        public int KeenPictureId {
            get {
                return this.keenPictureIdField;
            }
            set {
                this.keenPictureIdField = value;
            }
        }
        
        /// <remarks/>
        public string KeenName {
            get {
                return this.keenNameField;
            }
            set {
                this.keenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class AccountActivityQueryOptions {
        
        private string sortOrderField;
        
        private bool sortAscendingField;
        
        private bool picturesOnlyField;
        
        private bool bloggersOnlyField;
        
        private string countryField;
        
        private string stateField;
        
        private string cityField;
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        public string SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        public bool SortAscending {
            get {
                return this.sortAscendingField;
            }
            set {
                this.sortAscendingField = value;
            }
        }
        
        /// <remarks/>
        public bool PicturesOnly {
            get {
                return this.picturesOnlyField;
            }
            set {
                this.picturesOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool BloggersOnly {
            get {
                return this.bloggersOnlyField;
            }
            set {
                this.bloggersOnlyField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitAccount))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitAccountActivity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public abstract partial class TransitServiceOfAccount {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitAccountActivity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class TransitAccount : TransitServiceOfAccount {
        
        private bool isPasswordExpiredField;
        
        private System.DateTime createdField;
        
        private bool isAdministratorField;
        
        private string nameField;
        
        private System.DateTime birthdayField;
        
        private System.DateTime lastLoginField;
        
        private int pictureIdField;
        
        private string stateField;
        
        private string countryField;
        
        private string cityField;
        
        private int timeZoneField;
        
        private string signatureField;
        
        private string passwordField;
        
        /// <remarks/>
        public bool IsPasswordExpired {
            get {
                return this.isPasswordExpiredField;
            }
            set {
                this.isPasswordExpiredField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAdministrator {
            get {
                return this.isAdministratorField;
            }
            set {
                this.isAdministratorField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastLogin {
            get {
                return this.lastLoginField;
            }
            set {
                this.lastLoginField = value;
            }
        }
        
        /// <remarks/>
        public int PictureId {
            get {
                return this.pictureIdField;
            }
            set {
                this.pictureIdField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public int TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.vestris.com/sncore/ns/")]
    public partial class TransitAccountActivity : TransitAccount {
        
        private int newPicturesField;
        
        private int newDiscussionPostsField;
        
        private int newSyndicatedContentField;
        
        /// <remarks/>
        public int NewPictures {
            get {
                return this.newPicturesField;
            }
            set {
                this.newPicturesField = value;
            }
        }
        
        /// <remarks/>
        public int NewDiscussionPosts {
            get {
                return this.newDiscussionPostsField;
            }
            set {
                this.newDiscussionPostsField = value;
            }
        }
        
        /// <remarks/>
        public int NewSyndicatedContent {
            get {
                return this.newSyndicatedContentField;
            }
            set {
                this.newSyndicatedContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetNewAccountsCompletedEventHandler(object sender, GetNewAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccount[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetActiveAccountsCompletedEventHandler(object sender, GetActiveAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccount[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAccountActivityCountCompletedEventHandler(object sender, GetAccountActivityCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountActivityCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountActivityCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAccountActivityCompletedEventHandler(object sender, GetAccountActivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccountActivity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccountActivity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetNDegreeCountByIdCompletedEventHandler(object sender, GetNDegreeCountByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNDegreeCountByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNDegreeCountByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetFirstDegreeCountByIdCompletedEventHandler(object sender, GetFirstDegreeCountByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFirstDegreeCountByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFirstDegreeCountByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetFriendsAccountActivityCountCompletedEventHandler(object sender, GetFriendsAccountActivityCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendsAccountActivityCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendsAccountActivityCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetFriendsAccountActivityCompletedEventHandler(object sender, GetFriendsAccountActivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendsAccountActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendsAccountActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccountActivity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccountActivity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CreateOrUpdateAccountFriendRequestCompletedEventHandler(object sender, CreateOrUpdateAccountFriendRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateAccountFriendRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateAccountFriendRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AcceptAccountFriendRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void RejectAccountFriendRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetSentAccountFriendRequestsCountCompletedEventHandler(object sender, GetSentAccountFriendRequestsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSentAccountFriendRequestsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSentAccountFriendRequestsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAccountFriendRequestsCountCompletedEventHandler(object sender, GetAccountFriendRequestsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountFriendRequestsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountFriendRequestsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetSentAccountFriendRequestsCompletedEventHandler(object sender, GetSentAccountFriendRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSentAccountFriendRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSentAccountFriendRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccountFriendRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccountFriendRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAccountFriendRequestsCompletedEventHandler(object sender, GetAccountFriendRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountFriendRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountFriendRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccountFriendRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccountFriendRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteAccountFriendRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAccountFriendRequestByIdCompletedEventHandler(object sender, GetAccountFriendRequestByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountFriendRequestByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountFriendRequestByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccountFriendRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccountFriendRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteAccountFriendCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAccountFriendsCountCompletedEventHandler(object sender, GetAccountFriendsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountFriendsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountFriendsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAccountFriendsCompletedEventHandler(object sender, GetAccountFriendsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountFriendsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountFriendsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitAccountFriend[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitAccountFriend[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591